---
server.port: 8090


my:
    password : ${random.name}
    greetings: Hello Abhi from test ${my.password}
    
  



db:
   values: "{dbNameString:'MySQL', userName:'abhi', password:'1234'}"
   name: Oracle
   host: 130.0.0.0
   port: 8000

management.endpoints.web.exposure.include: "*"
